<?php

namespace App\Enums;

use Filament\Support\Contracts\HasLabel;


enum SurahEnum: int implements HasLabel
{
    case AL_FATIHAH = 1;
    case AL_BAQARAH = 2;
    case ALI_UMRAN = 3;
    case AN_NISA = 4;
    case AL_MAIDAH = 5;
    case AL_ANAM = 6;
    case AL_ARAF = 7;
    case AL_ANFAL = 8;
    case AT_TAUBAH = 9;
    case YUNUS = 10;
    case HUD = 11;
    case YUSUF = 12;
    case AR_RAD = 13;
    case IBRAHIM = 14;
    case AL_HIJR = 15;
    case AN_NAHL = 16;
    case AL_ISRA = 17;
    case AL_KAHF = 18;
    case MARYAM = 19;
    case TAHA = 20;
    case AL_ANBIYA = 21;
    case AL_HAJJ = 22;
    case AL_MUUMINUN = 23;
    case AN_NUR = 24;
    case AL_FURQAN = 25;
    case ASH_SHUARA = 26;
    case AN_NAML = 27;
    case AL_QASAS = 28;
    case AL_ANKABUT = 29;
    case AR_RUM = 30;
    case LUQMAN = 31;
    case AS_SAJDAH = 32;
    case AL_AHZAB = 33;
    case SABA = 34;
    case FATIR = 35;
    case YA_SIN = 36;
    case AS_SAFFAT = 37;
    case SAD = 38;
    case AZ_ZUMAR = 39;
    case GHAFIR = 40;
    case FUSSILAT = 41;
    case ASH_SHURA = 42;
    case AZ_ZUKHRUF = 43;
    case AD_DUKHAN = 44;
    case AL_JATHIYA = 45;
    case AL_AHQAF = 46;
    case MUHAMMAD = 47;
    case AL_FATH = 48;
    case AL_HUJURAT = 49;
    case QAF = 50;
    case ADH_DHARIYAT = 51;
    case AT_TUR = 52;
    case AN_NAJM = 53;
    case AL_QAMAR = 54;
    case AR_RAHMAN = 55;
    case AL_WAQIAAH = 56;
    case AL_HADID = 57;
    case AL_MUJADILAH = 58;
    case AL_HASHR = 59;
    case AL_MUMTAHINAH = 60;
    case AS_SAFF = 61;
    case AL_JUMUAH = 62;
    case AL_MUNAFIQUN = 63;
    case AT_TAGHABUN = 64;
    case AT_TALAQ = 65;
    case AT_TAHRIM = 66;
    case AL_MULK = 67;
    case AL_QALAM = 68;
    case AL_HAAQQAH = 69;
    case AL_MAARIJ = 70;
    case NUH = 71;
    case AL_JINN = 72;
    case AL_MUZZAMMIL = 73;
    case AL_MUDDATHTHIR = 74;
    case AL_QIYAMAH = 75;
    case AL_INSAN = 76;
    case AL_MURSALAT = 77;
    case AN_NABA = 78;
    case AN_NAZIAT = 79;
    case ABASA = 80;
    case AT_TAKWIR = 81;
    case AL_INFITHAR = 82;
    case AL_MUTAFFIFIN = 83;
    case AL_INSHIQAQ = 84;
    case AL_BURUJ = 85;
    case AT_TARIQ = 86;
    case AL_ALA = 87;
    case AL_GHASHIYAH = 88;
    case AL_FAJR = 89;
    case AL_BALAD = 90;
    case ASH_SHAMS = 91;
    case AL_LAIL = 92;
    case AD_DUHA = 93;
    case ASH_SHARH = 94;
    case AT_TIN = 95;
    case AL_ALAQ = 96;
    case AL_QADR = 97;
    case AL_BAYYINAH = 98;
    case AZ_ZALZALAH = 99;
    case AL_ADIYAT = 100;
    case AL_QARIAH = 101;
    case AT_TAKATHUR = 102;
    case AL_ASR = 103;
    case AL_HUMAZAH = 104;
    case AL_FIL = 105;
    case QURAYSH = 106;
    case AL_MAUN = 107;
    case AL_KAWTHAR = 108;
    case AL_KAFIRUN = 109;
    case AN_NASR = 110;
    case AL_MASAD = 111;
    case AL_IKHLAS = 112;
    case AL_FALAQ = 113;
    case AN_NAS = 114;

    public function getSurahName(): string|null
    {
        return self::getLabel();
    }
    public function getLabel(): string|null
    {
        return match ($this) {
            self::AL_FATIHAH => 'الفاتحة',
            self::AL_BAQARAH => 'البقرة',
            self::ALI_UMRAN => 'آل عمران',
            self::AN_NISA => 'النساء',
            self::AL_MAIDAH => 'المائدة',
            self::AL_ANAM => 'الأنعام',
            self::AL_ARAF => 'الأعراف',
            self::AL_ANFAL => 'الأنفال',
            self::AT_TAUBAH => 'التوبة',
            self::YUNUS => 'يونس',
            self::HUD => 'هود',
            self::YUSUF => 'يوسف',
            self::AR_RAD => 'الرعد',
            self::IBRAHIM => 'إبراهيم',
            self::AL_HIJR => 'الحجر',
            self::AN_NAHL => 'النحل',
            self::AL_ISRA => 'الإسراء',
            self::AL_KAHF => 'الكهف',
            self::MARYAM => 'مريم',
            self::TAHA => 'طه',
            self::AL_ANBIYA => 'الأنبياء',
            self::AL_HAJJ => 'الحج',
            self::AL_MUUMINUN => 'المؤمنون',
            self::AN_NUR => 'النور',
            self::AL_FURQAN => 'الفرقان',
            self::ASH_SHUARA => 'الشعراء',
            self::AN_NAML => 'النمل',
            self::AL_QASAS => 'القصص',
            self::AL_ANKABUT => 'العنكبوت',
            self::AR_RUM => 'الروم',
            self::LUQMAN => 'لقمان',
            self::AS_SAJDAH => 'السجدة',
            self::AL_AHZAB => 'الأحزاب',
            self::SABA => 'سبأ',
            self::FATIR => 'فاطر',
            self::YA_SIN => 'يس',
            self::AS_SAFFAT => 'الصافات',
            self::SAD => 'ص',
            self::AZ_ZUMAR => 'الزمر',
            self::GHAFIR => 'غافر',
            self::FUSSILAT => 'فصلت',
            self::ASH_SHURA => 'الشورى',
            self::AZ_ZUKHRUF => 'الزخرف',
            self::AD_DUKHAN => 'الدخان',
            self::AL_JATHIYA => 'الجاثية',
            self::AL_AHQAF => 'الأحقاف',
            self::MUHAMMAD => 'محمد',
            self::AL_FATH => 'الفتح',
            self::AL_HUJURAT => 'الحجرات',
            self::QAF => 'ق',
            self::ADH_DHARIYAT => 'الذاريات',
            self::AT_TUR => 'الطور',
            self::AN_NAJM => 'النجم',
            self::AL_QAMAR => 'القمر',
            self::AR_RAHMAN => 'الرحمن',
            self::AL_WAQIAAH => 'الواقعة',
            self::AL_HADID => 'الحديد',
            self::AL_MUJADILAH => 'المجادلة',
            self::AL_HASHR => 'الحشر',
            self::AL_MUMTAHINAH => 'الممتحنة',
            self::AS_SAFF => 'الصف',
            self::AL_JUMUAH => 'الجمعة',
            self::AL_MUNAFIQUN => 'المنافقون',
            self::AT_TAGHABUN => 'التغابن',
            self::AT_TALAQ => 'الطلاق',
            self::AT_TAHRIM => 'التحريم',
            self::AL_MULK => 'الملك',
            self::AL_QALAM => 'القلم',
            self::AL_HAAQQAH  => 'الحاقة',
            self::AL_MAARIJ => 'المعارج',
            self::NUH => 'نوح',
            self::AL_JINN => 'الجن',
            self::AL_MUZZAMMIL => 'المزمل',
            self::AL_MUDDATHTHIR => 'المدثر',
            self::AL_QIYAMAH => 'القيامة',
            self::AL_INSAN  => 'الإنسان',
            self::AL_MURSALAT => 'المرسلات',
            self::AN_NABA => 'النبأ',
            self::AN_NAZIAT => 'النازعات',
            self::ABASA => 'عبس',
            self::AT_TAKWIR => 'التكوير',
            self::AL_INFITHAR => 'الانفطار',
            self::AL_MUTAFFIFIN => 'المطففين',
            self::AL_INSHIQAQ => 'الانشقاق',
            self::AL_BURUJ => 'البروج',
            self::AT_TARIQ => 'الطارق',
            self::AL_ALA => 'الأعلى',
            self::AL_GHASHIYAH  => 'الغاشية',
            self::AL_FAJR => 'الفجر',
            self::AL_BALAD => 'البلد',
            self::ASH_SHAMS => 'الشمس',
            self::AL_LAIL => 'الليل',
            self::AD_DUHA => 'الضحى',
            self::ASH_SHARH => 'الشرح',
            self::AT_TIN => 'التين',
            self::AL_ALAQ => 'العلق',
            self::AL_QADR => 'القدر',
            self::AL_BAYYINAH => 'البينة',
            self::AZ_ZALZALAH => 'الزلزلة',
            self::AL_ADIYAT => 'العاديات',
            self::AL_QARIAH => 'القارعة',
            self::AT_TAKATHUR => 'التكاثر',
            self::AL_ASR => 'العصر',
            self::AL_HUMAZAH => 'الهمزة',
            self::AL_FIL => 'الفيل',
            self::QURAYSH => 'قريش',
            self::AL_MAUN => 'الماعون',
            self::AL_KAWTHAR => 'الكوثر',
            self::AL_KAFIRUN => 'الكافرون',
            self::AN_NASR => 'النصر',
            self::AL_MASAD => 'المسد',
            self::AL_IKHLAS => 'الإخلاص',
            self::AL_FALAQ => 'الفلق',
            self::AN_NAS => 'الناس',
        };
    }

    public function getSoraAyaCount(): int
    {
        return match ($this) {
            self::AL_FATIHAH => 7,
            self::AL_BAQARAH => 286,
            self::ALI_UMRAN => 200,
            self::AN_NISA => 176,
            self::AL_MAIDAH => 120,
            self::AL_ANAM => 165,
            self::AL_ARAF => 206,
            self::AL_ANFAL => 75,
            self::AT_TAUBAH => 129,
            self::YUNUS => 109,
            self::HUD => 123,
            self::YUSUF => 111,
            self::AR_RAD => 43,
            self::IBRAHIM => 52,
            self::AL_HIJR => 99,
            self::AN_NAHL => 128,
            self::AL_ISRA => 111,
            self::AL_KAHF => 110,
            self::MARYAM => 98,
            self::TAHA => 135,
            self::AL_ANBIYA => 112,
            self::AL_HAJJ => 78,
            self::AL_MUUMINUN => 118,
            self::AN_NUR => 64,
            self::AL_FURQAN => 77,
            self::ASH_SHUARA => 227,
            self::AN_NAML => 93,
            self::AL_QASAS => 88,
            self::AL_ANKABUT => 69,
            self::AR_RUM => 60,
            self::LUQMAN => 34,
            self::AS_SAJDAH => 30,
            self::AL_AHZAB => 73,
            self::SABA => 54,
            self::FATIR => 45,
            self::YA_SIN => 83,
            self::AS_SAFFAT => 182,
            self::SAD => 88,
            self::AZ_ZUMAR => 75,
            self::GHAFIR => 85,
            self::FUSSILAT => 54,
            self::ASH_SHURA => 53,
            self::AZ_ZUKHRUF => 89,
            self::AD_DUKHAN => 59,
            self::AL_JATHIYA => 37,
            self::AL_AHQAF => 35,
            self::MUHAMMAD => 38,
            self::AL_FATH => 29,
            self::AL_HUJURAT => 18,
            self::QAF => 45,
            self::ADH_DHARIYAT => 60,
            self::AT_TUR => 49,
            self::AN_NAJM => 62,
            self::AL_QAMAR => 55,
            self::AR_RAHMAN => 78,
            self::AL_WAQIAAH => 96,
            self::AL_HADID => 29,
            self::AL_MUJADILAH => 22,
            self::AL_HASHR => 24,
            self::AL_MUMTAHINAH => 13,
            self::AS_SAFF => 14,
            self::AL_JUMUAH => 11,
            self::AL_MUNAFIQUN => 11,
            self::AT_TAGHABUN => 18,
            self::AT_TALAQ => 12,
            self::AT_TAHRIM => 12,
            self::AL_MULK => 30,
            self::AL_QALAM => 52,
            self::AL_HAAQQAH => 52,
            self::AL_MAARIJ => 44,
            self::NUH => 28,
            self::AL_JINN => 28,
            self::AL_MUZZAMMIL => 20,
            self::AL_MUDDATHTHIR => 56,
            self::AL_QIYAMAH => 40,
            self::AL_INSAN => 31,
            self::AL_MURSALAT => 50,
            self::AN_NABA => 40,
            self::AN_NAZIAT => 46,
            self::ABASA => 42,
            self::AT_TAKWIR => 29,
            self::AL_INFITHAR => 19,
            self::AL_MUTAFFIFIN => 36,
            self::AL_INSHIQAQ => 25,
            self::AL_BURUJ => 22,
            self::AT_TARIQ => 17,
            self::AL_ALA => 19,
            self::AL_GHASHIYAH => 26,
            self::AL_FAJR => 30,
            self::AL_BALAD => 20,
            self::ASH_SHAMS => 15,
            self::AL_LAIL => 21,
            self::AD_DUHA => 11,
            self::ASH_SHARH => 8,
            self::AT_TIN => 8,
            self::AL_ALAQ => 19,
            self::AL_QADR => 5,
            self::AL_BAYYINAH => 8,
            self::AZ_ZALZALAH => 8,
            self::AL_ADIYAT => 11,
            self::AL_QARIAH => 11,
            self::AT_TAKATHUR => 8,
            self::AL_ASR => 3,
            self::AL_HUMAZAH => 9,
            self::AL_FIL => 5,
            self::QURAYSH => 4,
            self::AL_MAUN => 7,
            self::AL_KAWTHAR => 3,
            self::AL_KAFIRUN => 6,
            self::AN_NASR => 3,
            self::AL_MASAD => 5,
            self::AL_IKHLAS => 4,
            self::AL_FALAQ => 5,
            self::AN_NAS => 6,
        };
    }
}
